### ISSUE TITLE
HEIC support

### ISSUE THREAD

**Issue by unmade** [unmade/shelf-back#105]

**Comment by bigcat88** [comment]
`from pillow_heif import HeifImagePlugin`

that's all.

**Comment by unmade** [comment]
Hey, @bigcat88

I've actually already found your library and **big** thanks for that!

I probably go with `pi-heif` though to be compliant with license. My main use-case is to make thumbnails for different image formats anyway.

I also need to read exif information from `HEIC` image. Currently, I'm relying on pillow `_getexif` method, but for HEIC it gives me `AttributeError`, so I need to research that a bit

Wasn't expecting someone to find that issue, so was a little bit lazy to fill in the description ;)

**Comment by bigcat88** [comment]
license is equal for both projects

**Comment by bigcat88** [comment]
> I also need to read exif information from `HEIC` image. Currently, I'm relying on pillow `_getexif` method, but for HEIC it gives me `AttributeError`, so I need to research that a bit

that's strange, I have tests for EXIF in repository...

**Comment by unmade** [comment]
`.getexif()` works just as expected. However it gives significantly less information compared to private `._getexif()` method regardless whether the image is `heic` or `jpeg`

**Comment by unmade** [comment]
I probably just switch to [exifread](https://github.com/ianare/exif-py) to read EXIF

**Comment by bigcat88** [comment]
`.getexif` for `HEIF` files give all `exif` info. If not then it is probably a bug - can you provide some code and a test image file to see if it is?
For `JPEG` as I remember it is the same.

**Comment by unmade** [comment]
I'm testing on photos I took with iPhone 8. Here is sample images:
- [HEIC](https://www.dropbox.com/s/zv361943zriwtv6/IMG_5196.HEIC?dl=0)
- [JPEG](https://www.dropbox.com/s/odnb8pcrvesvcog/IMG_5196.jpg?dl=0)

The `.getexif()` method gives me following information:

```
{
    'TileWidth': 512,
    'TileLength': 512,
    'GPSInfo': 1728,
    'ResolutionUnit': 2,
    'ExifOffset': 230,
    'Make': 'Apple',
    'Model': 'iPhone 8',
    'Software': '11.3.1',
    'Orientation': 1,
    'DateTime': '2018:05:28 20:35:36',
    'YCbCrPositioning': 1,
    'XResolution': 72.0,
    'YResolution': 72.0
}
```

The `exifread` gives slightly more information, such as `ApertureValue`, `ShutterSpeedValue`, etc...:

```
{
    'Image Make': (0x010F) ASCII=Apple @ 170,
    'Image Model': (0x0110) ASCII=iPhone 8 @ 176,
    ...
    'GPS GPSLatitudeRef': (0x0001) ASCII=N @ 1738,
    'GPS GPSLatitude': (0x0002) Ratio=[52, 22, 389/20] @ 1902,
    ...
    'EXIF ExposureTime': (0x829A) Ratio=1/873 @ 620,
    'EXIF FNumber': (0x829D) Ratio=9/5 @ 628,
    ...
}
```

For JPEGs images Pillow's private `_getexif()` method also gives that "extended" information, but public `.getexif()` gives the short one. 

Here is a short script showing the difference between methods:
https://www.dropbox.com/s/37iq7cl0s2n22fu/exif.py?dl=0

Usage:
```bash
python3 exif.py IMG_5196.jpg
```

**Comment by bigcat88** [comment]
```
    im = Image.open("IMG_5196.HEIC")
    img_exif = im.getexif()._get_merged_dict()
    for key, val in img_exif.items():
        if key in ExifTags.TAGS:
            print(f'{ExifTags.TAGS[key]}:{val}')
```

**Comment by bigcat88** [comment]
https://github.com/python-pillow/Pillow/issues/6641#issuecomment-1268583808

**Comment by unmade** [comment]
Works like a charm! I had to go deeper with `getexif()` method :)

Thank you so much for helping me out!
