### ISSUE TITLE
s3-like storage

### ISSUE THREAD

**Issue by myrsk** [unmade/shelf-back#136]
Thanks for the great project @unmade !

I looked at some of the code, and it seems that the s3 endpoint url is not something that we can pass in the ENV variables. Am i missing something? Can I not pass an endpoint of a s3 compatible storage? Like my own minio etc?

Thanks.

**Comment by unmade** [comment]
Hey, @myrsk 

Thanks for checking out the project!

You can pass custom S3 location, please use the following env variables:

```
STORAGE_LOCATION="https://s3.com"
STORAGE_S3_ACCESS_KEY_ID="your_access_id"
STORAGE_S3_SECRET_ACCESS_KEY="your_access_key"
STORAGE_S3_BUCKET_NAME="shelf"
STORAGE_S3_REGION_NAME=""
```

**Comment by myrsk** [comment]
Ah!, Thanks for the quick reply. I did not have https:// infront of the endpoint ... that could have been the issue.

Thanks again!
